### ISSUE TITLE
Documentation: Configuration Migrations

### ISSUE THREAD

**Issue by nkabir** [sprin/pg-discuss#14]
There seems to be content missing after _run:_

...
Migrations for bundled extensions are located in a separate directory. If any of the bundled extensions are used, we need to also run:
...

http://pg-discuss.sprin.io/en/latest/configuration.html

**Comment by sprin** [comment]
Thanks! I will update that section tonight.

This project has yet to reach 1.0 beta and be posted to PyPI, but I'd be happy to hear your experience if you've installed from the current git master. I will be making the first beta release sometime this week.

**Comment by nkabir** [comment]
I'm looking forward to it! It would be helpful if you included the source code for the demo site. It's not clear how all the pieces are supposed to fit together in an actual deployment.
