### ISSUE TITLE
Demo sites down

### ISSUE THREAD

**Issue by arktype** [sprin/pg-discuss#22]
Heads up: the demo sites are down. It looks like the JS frontend isn't loading

http://pg-discuss.sprin.io/en/latest/demo.html

**Comment by sprin** [comment]
Thanks so much for the heads up!

I have been hosting this on my own server in California, and I've been living elsewhere for some months. It seems I forgot to configure the machine to automatically reboot after power loss. Also, I did not finish the monitoring config before leaving!

I'll be moving the demo service to a cloud-hosted Sandstorm deployment upon return to California.

**Comment by sprin** [comment]
The primary demo is back online on a cloud deployment. Will set up the admin demo and the "many comments" demo soon.

https://pg-discuss.sprin.io/en/latest/demo.html

**Comment by sprin** [comment]
The other demos are up:
https://pg-discuss.sprin.io/en/latest/_static/got_six_weeks.html
https://pg-discuss.sprin.io/en/latest/admin-demo.html

The process of redeploying has surfaced some bugs: #25, #26.
